spring.application.name=KW-SPACE
kw-space.auth.cookie.access-token-name=accessToken
kw-space.auth.cookie.secure=true
kw-space.auth.cookie.http-only=true
kw-space.auth.cookie.same-site=Lax
kw-space.auth.cookie.path=/
kw-space.auth.cookie.max-age=3600s
