spring.application.name=KW-SPACE
spring.config.import=optional:file:.env[.properties]
kw-space.auth.jwt.secret=${KW_SPACE_AUTH_JWT_SECRET:}
kw-space.auth.jwt.access-token-ttl=${KW_SPACE_AUTH_JWT_ACCESS_TOKEN_TTL:1h}
kw-space.auth.cookie.access-token-name=accessToken
kw-space.auth.cookie.secure=true
kw-space.auth.cookie.http-only=true
kw-space.auth.cookie.same-site=Lax
kw-space.auth.cookie.path=/
kw-space.auth.cookie.max-age=3600s
